app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView
from django.urls import path, include

from app.views import *

urlpatterns = [path('', index),
               path('login/', LoginFormView.as_view(), name='login'),
               path('logout/', LogoutView.as_view(), name='logout'),
               path('principal/', PrincipalTemplateView.as_view(), name='principal'),

               # -------------------------------------------------------
               # ----------- Local Básico URLS ------------
               # -------------------------------------------------------

               path('local/',
                    localListView.as_view(),
                    name='local'),

               path('local/add/',
                    localCreateView.as_view(),
                    name='add_local'),

               path('local/edit/<int:pk>/',
                    localUpdateView.as_view(),
                    name='editar_local'),

               path('local/delete/<int:pk>/',
                    localDeleteView.as_view(),
                    name='eliminar_local'),
               
               # -------------------------------------------------------
               # ----------- Planillas URLS ------------
               # -------------------------------------------------------

               path('Planilla/',
                    PlanillaListView.as_view(),
                    name='planilla'),

               path('Planilla/edit/<int:pk>/',
                    PlanillaUpdateView.as_view(),
                    name='editar_planilla'),

               path('Planilla/detalles/<int:pk>/',
                    details,
                    name='detalles_planilla'),
               
               # -------------------------------------------------------
               # ----------- Medio Básico URLS ------------
               # -------------------------------------------------------

               path('MedioBasico/',
                    MedioBasicoListView.as_view(),
                    name='medio'),

               path('MedioBasico/add/',
                    MedioBasicoCreateView.as_view(),
                    name='add_medio'),

               path('MedioBasico/edit/<int:pk>/',
                    MedioBasicoUpdateView.as_view(),
                    name='editar_medio'),

               path('MedioBasico/delete/<int:pk>/',
                    MedioBasicoDeleteView.as_view(),
                    name='eliminar_medio'),
               
               # -------------------------------------------------------
               # ----------- Usuarios URLS ------------
               # -------------------------------------------------------

               path('Usuario/',
                    UsuarioListView.as_view(),
                    name='user'),

               path('Usuario/add/',
                    UsuarioCreateAdminView.as_view(),
                    name='add_user'),

               path('Usuario/edit/<int:pk>/',
                    UsuarioUpdateView.as_view(),
                    name='editar_user'),

               path('Usuario/delete/<int:pk>/',
                    UsuarioDeleteView.as_view(),
                    name='eliminar_user'),


               ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

djangoProject1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),


]

app/models.py
from django.db import models
from django.utils.translation import gettext_lazy as T
from django.core.validators import RegexValidator, MinValueValidator
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager
from django.utils.translation import gettext_lazy as T

validate_username = RegexValidator('^[A-Za-z\d]*$', 'Solo Letras y numeros , sin espacios')

validate_mb = RegexValidator('^(MB|MB-)\d{8,}$', 'Identificador Inválido')
tfno_regex = RegexValidator('^\+53\d{8}$', 'Teléfono invalido')
validate_ci = RegexValidator('^\d{2}(?:0[1-9]|1[0-2])(?:0[1-9]|[12]\d|3[01])\d{5}$', 'Carnet invalido')
validate_name = RegexValidator('^[A-Za-záãäéëêíîóöúüñç\s]*$', 'Solo Letras')

# Create your models here.

# Create your models here.
class OwnUserManager(BaseUserManager):
    """Manager para usuarios"""
    use_in_migrations = True

    def create_user(self, username, name, apellidos,  ci, tfno, password=None, **extra_kwargs):
        """Crea un nuevo Usuario"""
        if not username:
            raise ValueError("El nombre de usuario no puede estar vacio")

        user = self.model(username=username, name=name,
                          apellidos=apellidos, ci=ci, tfno=tfno, **extra_kwargs)

        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, username, name, apellidos,  ci, tfno, password=None, **extra_kwargs):
        user = self.create_user(username, name, apellidos, ci, tfno,
                                password, **extra_kwargs)

        user.is_superuser = True
        user.is_staff = True
        user.set_password(password)
        user.save()
        return user


class User(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=255, unique=True, validators=[validate_username])
    name = models.CharField(max_length=255 , validators=[validate_name])
    apellidos = models.CharField(max_length=255 , validators=[validate_name])
    ci = models.CharField(max_length=11, unique=True, null=False, blank=False, validators=[validate_ci])
    tfno = models.CharField(max_length=50 , validators=[tfno_regex])
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    
    objects = OwnUserManager()
    
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['name', 'apellidos', 'ci', 'tfno']

    def get_full_name(self):
        return "%s %s" % (self.name, self.apellidos)

    def get_short_name(self):
        return self.name

    def __str__(self):
        return (self.name)

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def if_staff(self):
        return self.is_staff

class estado (models.TextChoices):
        bueno= 'B', T('Bueno')
        regular= 'R', T('Regular')
        malo = 'M', T('Malo')
        
class tipo (models.TextChoices):
        aula= 'A', T('Aula')
        salon= 'S', T('Salon')
        laboratorio = 'L', T('Laboratorio')
        departamento = 'D', T('Departamento')
        

class Local(models.Model):
    
    nombre = models.CharField(max_length=255)
    
    tipo = models.CharField(max_length=255,choices=tipo.choices)
    
    def __str__(self):
        return self.nombre

class MedioBasico(models.Model):
    
    mb = models.CharField(max_length=255, validators=[validate_mb])
    
    tipo = models.CharField(max_length=15,null=False,blank=False)
    
    local = models.ForeignKey(Local, on_delete = models.CASCADE)

    estado = models.CharField(max_length=255, verbose_name='estado',
                                     choices=estado.choices, null=False, blank=False)

    def __str__(self):
        return self.tipo

class estadomedioBasico (models.TextChoices):
        pendiente= 'P', T('Pendiente')
        aprobado= 'A', T('Aprobado')
        denegado = 'D', T('Denegado')

class Planilla(models.Model):
        
        local = models.OneToOneField(Local, on_delete=models.CASCADE,primary_key=True)
        
        fecha =  models.DateField(blank=False, null=False, auto_now=True)
    
        faltante = models.IntegerField(default=0,blank=True, null=True,validators=[MinValueValidator(0 , "La cantidad debe ser mayor o igual a 0")])
    
        sobrante = models.IntegerField(default=0,blank=True, null=True,validators=[MinValueValidator(0 , "La cantidad debe ser mayor o igual a 0")])
    
        estado = models.CharField(max_length=255,choices=estadomedioBasico.choices, null=False, blank=False,default='P')


        def __str__(self):
                return self.estado

        

app/templates/locales/add.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    {{title}}
{% endblock title %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'css/dashboard/dashboard.css' %}">
{% endblock styles %}

{% block content %}
    {% include "header.html" %}

    <div class="container-fluid">
        <div class="row">
            {# SideBar #}

            {% include "sidebar.html" %}

            {#Container principal#}
            <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4 pb-5 scrollarea">
                <div class="container mt-3">
                    <h1 class="fs-5">{{ title }}</h1>
                </div>
                <!--------------------------------------------------------------------------------------
                   -----------------TABLA CON RESULTADOS DE LAS ENTIDADES------------------------------------
                   -------------------------------------------------------------------------------------------->
                <div class="container mb-5">
                    <div class="card">
                        <div class="card-body">
                            <form action="." method="post"
                                  id="form_insertar_entidad">
                                {% csrf_token %}

                                {% if form.errors %}
                                    <div class="alert alert-danger sm mb-3 p-2" role="alert">
                                        <h6>Ha ocurrido un error al intentar guardar el Local</h6>
                                    </div>
                                {% endif %}
                                <div class="row">
                                    <div class="col-12">
                                        <!--IMPUT NOMBRE ENTIDAD-->
                                        <div class=" mb-4 position-relative">

                                            <label class="form-label">Local:</label>
                                                {{form.nombre}}
                                            {% if form.nombre.errors %}
                                                <div class="alert alert-danger sm m-1 p-2 small" role="alert">
                                                    {% for error in form.nombre.errors %}
                                                        {{ error }}
                                                    {% endfor %}
                                                </div>
                                            {% endif %}
                                        </div>
                                    </div>
                                    <div class="col-12 col-lg-6">
                                        <div class="mb-4 position-relative">
                                            <label for="{{ form.telefonoEntidad.id_for_label }}"
                                                   class="form-label">Tipo:</label>
                                                   {{form.tipo}}
                                            {% if form.tipo.errors %}
                                                <div class="alert alert-danger sm m-1 p-2 small" role="alert">
                                                    {% for error in form.tipo.errors %}
                                                        {{ error }}
                                                    {% endfor %}
                                                </div>
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                                <div class=" position-relative">
                                    <a class="text-decoration-none" href="{% url 'local'%}">
                                        <button type="button"
                                                class="btn btn-secondary rounded-0"
                                                data-bs-dismiss="modal">Cancelar
                                        </button>
                                    </a>

                                    <button type="submit" class="btn btn-success rounded-0" id="btnappend">
                                        Guardar
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>

                </div>

            </main>


        </div>
    </div>


    {#    {% include "footer.html" %}#}
{% endblock content %}

{% block scripts %}


    <script type="application/javascript">
        $(function () {
            $('#entidadTable').DataTable({
                responsive: true,
                "language": {
                    url: '{% static 'lib/es-ES.json ' %}'
                }
            });
        });
    </script>
{% endblock scripts %}

app/templates/locales/delete.html
{% extends "base.html" %}
{% load static %}


{% block styles %}
    <link rel="stylesheet" href="{% static 'css/dashboard/dashboard.css' %}">

{% endblock styles %}

{% block title %}
    {{ title }}
{% endblock title %}

{% block content %}

    {% include "header.html" %}

    <div class="container-fluid">
        <div class="row">
            {# SideBar #}

            {% include "sidebar.html" %}
            {#Container principal#}
            <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4 pb-5 scrollarea">
                <div class="container mt-3">
                    <h1 class="fs-5">¿Está seguro? </h1>
                </div>
                <div class="card">
                    <div class="card-body">
                        <div class="content">
                            <p class="fs-6">¿Está usted seguro que quiere eliminar el Local seleccionado?:</p>
                            <ul>
                                <li>
                                    <strong>{{ object.nombre }}</strong>
                                </li>
                            </ul>
                            <!-- Content -->
                            <form method="post">
                                {% csrf_token %}
                                <input class="button btn btn-danger rounded-0" type="submit" value="Si, estoy seguro">
                                <a class="text-decoration-none" href="{% url 'local'%}">
                                    <button type="button" class="btn btn-secondary rounded-0"
                                            data-bs-dismiss="modal">Cancelar
                                    </button>
                                </a>
                            </form>
                            <!-- END Content -->
                            <div id="footer"></div>
                        </div>
                    </div>
                </div>
            </main>
        </div>
    </div>


    {#    {% include "footer.html" %}#}
{% endblock content %}

{% block scripts %}


{% endblock scripts %}

app/templates/locales/edit.html
{% extends "base.html" %}
{% load static %}


{% block styles %}
    <link rel="stylesheet" href="{% static 'css/dashboard/dashboard.css' %}">

{% endblock styles %}

{% block title %}
    {{ title }}
{% endblock title %}

{% block content %}

    {% include "header.html" %}

    <div class="container-fluid">
        <div class="row">
            {# SideBar #}

            {% include "sidebar.html" %}
            {#Container principal#}
            <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4 pb-5  scrollarea">
                <div class="container mt-3">
                    <h1 class="fs-5">Editar entidad <span class="fs-4">{{ object.nombreEntidad }}</span></h1>

                </div>

                <div class="container-md">
                    <div class="card">
                        <div class="card-body">
                            <form method="post">

                                {% csrf_token %}

                                {% if form.errors %}
                                <div class="alert alert-danger sm mb-3 p-2" role="alert">
                                    <h6>Ha ocurrido un error al intentar guardar el Local</h6>
                                </div>
                            {% endif %}
                            <div class="row">
                                <div class="col-12">
                                    <!--IMPUT NOMBRE ENTIDAD-->
                                    <div class=" mb-4 position-relative">

                                        <label class="form-label">Local:</label>
                                            {{form.nombre}}
                                        {% if form.nombre.errors %}
                                            <div class="alert alert-danger sm m-1 p-2 small" role="alert">
                                                {% for error in form.nombre.errors %}
                                                    {{ error }}
                                                {% endfor %}
                                            </div>
                                        {% endif %}
                                    </div>
                                </div>
                                <div class="col-12 col-lg-6">
                                    <div class="mb-4 position-relative">
                                        <label for="{{ form.telefonoEntidad.id_for_label }}"
                                               class="form-label">Tipo:</label>
                                               {{form.tipo}}
                                        {% if form.telefonoEntidad.errors %}
                                            <div class="alert alert-danger sm m-1 p-2 small" role="alert">
                                                {% for error in form.telefonoEntidad.errors %}
                                                    {{ error }}
                                                {% endfor %}
                                            </div>
                                        {% endif %}
                                    </div>
                                </div>
                            
                            </div>
                            <div class=" position-relative">
                                <a class="text-decoration-none" href="{% url 'local' %}">
                                    <button type="button"
                                            class="btn btn-secondary rounded-0"
                                            data-bs-dismiss="modal">Cancelar
                                    </button>
                                </a>

                                <button type="submit" class="btn btn-success rounded-0" id="btnappend">
                                    Guardar
                                </button>
                            </div>
                            </form>
                        </div>
                    </div>
                </div>

            </main>
        </div>
    </div>


    {#    {% include "footer.html" %}#}
{% endblock content %}

{% block scripts %}


{% endblock scripts %}

app/templates/locales/index.html
{% extends "base.html" %}
{% load static %}



{% block title %}
    {{title}}
{% endblock title %}


{% block styles %}
    <link rel="stylesheet" href="{% static 'css/dashboard/dashboard.css' %}">


{% endblock styles %}

{% block content %}

    {% include "header.html" %}

    <div class="container-fluid">
        <div class="row">
            {#    SideBar      #}
            {% include "sidebar.html" %}

            {#Container principal#}
            <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4 pb-5 scrollarea">
                <div class="container mt-3 ">
                    <h1 class="fs-5">Locales</h1>
                </div>

                <!--------------------------------------------------------------------------------------
                    -----------------TABLA CON RESULTADOS DE LOCALES ------------------------------------
                    -------------------------------------------------------------------------------------------->

                {% comment %} ----------------------------------------------------------------------------
                -------------------------------BOTON INSERTAR LOCAL------------------------------------
                ---------------------------------------------------------------------------{% endcomment %}
                {% if perms.bugfinder.add_mediobasico %}
                    <div class="p-1">
                        <!-- Botón INSERTAR local -->
                        <a type="button" href="{% url 'add_local' %}"
                           class="btn p-0 border me-2  "
                           style="background-color: white"
                           title="Insertar nueva local">
                            <button class="btn rounded-0">
                                <img class="" src="{% static 'imag/bootstrap-icons/plus-circle.svg' %}"
                                     alt="Insertar Medio Básico" width="16" height="16">
                                Añadir Local
                            </button>
                        </a>
                    </div>
                {% endif %}
                <!--------------------------------------------------------------------------------------
               -----------------FIN BOTON INSERTAR LOCAL ------------------------------------
               -------------------------------------------------------------------------------------------->

                <div class="card border-0">
                    <div class="card-body">
                        <div class="table-responsive">
                            <table id="localTable" class="table table-hover table-sm ">
                                <thead>
                                <tr>
                                    <th scope="col" class="text-center" style="width: 50%">ID</th>
                                    <th scope="col" class="text-center" style="width: 15%">Nombre</th>
                                    <th scope="col" class="text-center" style="width: 25%">Tipo</th>
                                    {% if perms.app.change_local or perms.app.delete_local %}
                                        <th scope="col" class="text-center" style="width: 10%">Opciones</th>
                                    {% endif %}
                                </tr>
                                </thead>
                                <tbody>
                                {% csrf_token %}


                                {% for local in object_list %}
                                    <tr>
                                        <td class="text-center">{{ local.id | escape }}</td>
                                        <td class="text-center">{{ local.nombre | escape }}</td>
                                        <td class="text-center">{{ local.tipo | escape }}</td>
                                        {% if perms.app.change_local or perms.app.delete_local %}
                                            <td>
                                                {% if perms.bugfinder.change_mediobasico %}
                                                    <a id="" class=" mx-1 px-1 text-decoration-none" title="Editar"
                                                       href="{% url 'editar_local' local.id %}">
                                                        <img class=""
                                                             src="{% static 'imag/bootstrap-icons/pen.svg' %}"
                                                             alt="Modificar" width="14" height="14">
                                                    </a>
                                                {% endif %}
                                                {% if perms.bugfinder.delete_mediobasico %}
                                                    <a id="" class=" mx-1 px-1 text-decoration-none"
                                                       title="Eliminar"
                                                       href="{% url 'eliminar_local' local.id %}">

                                                        <img class=""
                                                             src="{% static 'imag/bootstrap-icons/trash.svg' %}"
                                                             alt="Eliminar" width="14" height="14">

                                                    </a>
                                                {% endif %}
                                            </td>
                                        {% endif %}
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
         <!--------------------------------------------------------------------------------------
           -----------------TABLA CON RESULTADOS DE LOCALES------------------------------------
           -------------------------------------------------------------------------------------------->
        </main>


    </div>
    </div>


    {#    {% include "footer.html" %}#}
{% endblock content %}

{% block scripts %}
    {% if messages %}
        {% for msg in messages %}
            <script>
                Swal.fire({'title' : "¡Hecho!" , "text" : "{{msg}}", "icon": "success"})
            </script>
        {% endfor %}
    {% endif %}
    <script type="application/javascript">
        $(function () {
            $('#localTable').DataTable({
                responsive: true,
                "language": {
                    url: '{% static 'lib/es-ES.json ' %}'
                }
            });
        });
    </script>
{% endblock scripts %}